export const SHORT_PROMPTS: string[] = [
  "Give me a 30-second overview of MattyJacks.",
  "What does MattyJacks actually do?",
  "Break down the MattyJacks companies in simple terms.",
  "What is GiveGigs and why does it matter?",
  "What makes CryptArtist Studio useful?",
  "Explain VentureCapitalArts like I’m new here.",
  "What is GraveGain about?",
  "Show me the best business opportunities in the ecosystem.",
  "How can I get involved with MattyJacks?",
  "What services does MattyJacks offer clients?",
  "What companies are under the MattyJacks umbrella?",
  "Which MattyJacks project is the most exciting right now?",
  "Give me a quick tour of the whole ecosystem.",
  "What are the main revenue streams here?",
  "How can I support or contribute to these projects?",
  "What can I learn from MattyJacks as a founder?",
  "What part of the ecosystem should I explore first?",
  "Tell me the story behind MattyJacks.",
  "What problems is MattyJacks solving?",
  "How does GiveGigs help freelancers?",
  "How does CryptArtist help creators?",
  "How does VCA make money funny?",
  "What’s the coolest part of GraveGain?",
  "What makes this ecosystem different from normal startups?",
  "Give me one reason to care about each company.",
  "What are the top MattyJacks websites to check out?",
  "What’s the fastest way to get value from the ecosystem?",
  "Help me think like a MattyJacks operator.",
  "What should I ask next to understand the business better?",
  "Turn me into a MattyJacks superfan.",
  "Explain MattyJacks in the most addictive way possible.",
  "What’s the craziest thing about the MattyJacks ecosystem?",
  "Why should someone pay attention to MattyJacks right now?",
  "Turn MattyJacks into a one-line viral hook.",
  "What makes GiveGigs instantly shareable?",
  "Why is CryptArtist secretly a big deal?",
  "Summarize the whole ecosystem like a startup thread.",
  "What’s the most underrated MattyJacks project?",
  "Give me the strongest ‘why this matters’ story for MattyJacks.",
  "What’s the most exciting thing I should know first?",
  "Make me curious about every MattyJacks company.",
  "What would make people talk about this ecosystem online?",
  "What’s the most impressive part of the MattyJacks stack?",
  "Give me a punchy pitch for the whole brand.",
  "What’s the most tweet-worthy thing here?",
  "How would you make MattyJacks go viral?",
  "What’s the boldest thing MattyJacks is building?",
  "What should I say if I want to sound obsessed with this brand?",
  "Explain why this ecosystem is bigger than it looks.",
  "Make me care about MattyJacks in 10 seconds.",
  "Explain MattyJacks like it’s a chaotic family business.",
  "Roast the ecosystem in a loving way.",
  "What if MattyJacks was a sitcom?",
  "Describe each company like a weird superhero.",
  "Make GiveGigs sound like a pirate freelancing guild.",
  "Explain CryptArtist like a wizard built a startup.",
  "Turn VentureCapitalArts into a fake infomercial.",
  "What would GraveGain look like if it had too much caffeine?",
  "Make the whole MattyJacks ecosystem sound unreasonably epic.",
  "Explain MattyJacks as if it were a tavern in a fantasy game.",
  "What’s the funniest way to pitch GiveGigs to a stranger?",
  "Describe the companies like they’re members of a dysfunctional band.",
  "If MattyJacks were a meme, what meme would it be?",
  "Make the ecosystem sound ridiculous but somehow legitimate.",
  "What’s the funniest company name in the group and why?",
  "Turn this whole business into a comedy trailer.",
  "Explain it like I’m a confused investor with too much coffee.",
  "What would a MattyJacks-themed stand-up bit sound like?",
  "Give me a silly but accurate summary of each company.",
  "Make me laugh while teaching me what MattyJacks does."
];
