// 100 Dynamic Chat Placeholders - Rotate every 4.20 seconds
// Supports [nickname] interpolation

export const CHAT_PLACEHOLDERS = [
  "Accomplish anything.",
  "Do it now.",
  "What's up today?",
  "Type in your dreams.",
  "Show me your fantasies.",
  "Upload images for me.",
  "Orders, [nickname]?",
  "Hey [nickname]!",
  "I love you, [nickname]",
  "What's on your mind?",
  "Tell me everything.",
  "Let's create magic.",
  "Show me what you've got.",
  "Surprise me, [nickname].",
  "What do you need?",
  "Ask me anything.",
  "I'm listening, [nickname].",
  "Make it happen.",
  "Let's go, [nickname]!",
  "What's the vision?",
  "Build something amazing.",
  "Show me your ideas.",
  "What's next, [nickname]?",
  "Let's break the internet.",
  "Create your masterpiece.",
  "What's your move?",
  "Unleash your creativity.",
  "Tell me your story.",
  "What do you want to create?",
  "Let's make history.",
  "Show me something wild.",
  "What's your next big thing?",
  "I'm ready, [nickname].",
  "Let's do this.",
  "What's cooking?",
  "Tell me a secret.",
  "What makes you tick?",
  "Show me your genius.",
  "What's the plan?",
  "Let's collaborate.",
  "What's your superpower?",
  "Tell me your truth.",
  "What inspires you?",
  "Let's create together.",
  "Show me your passion.",
  "What's your dream?",
  "Let's build empires.",
  "What's the big idea?",
  "Tell me something new.",
  "What's your edge?",
  "Let's change the world.",
  "Show me your potential.",
  "What's your story, [nickname]?",
  "Let's make waves.",
  "What's impossible for you?",
  "Tell me what matters.",
  "What's your legacy?",
  "Let's push boundaries.",
  "Show me your fire.",
  "What's your calling?",
  "Let's create legends.",
  "What's your vision, [nickname]?",
  "Tell me your why.",
  "What's your magic?",
  "Let's break records.",
  "Show me your heart.",
  "What's your mission?",
  "Let's build something eternal.",
  "What's your spark?",
  "Tell me your truth, [nickname].",
  "What's your art?",
  "Let's make it legendary.",
  "Show me your soul.",
  "What's your purpose?",
  "Let's create forever.",
  "What's your gift?",
  "Tell me everything, [nickname].",
  "What's your power?",
  "Let's make it count.",
  "Show me your brilliance.",
  "What's your essence?",
  "Let's leave a mark.",
  "What's your magic, [nickname]?",
  "Tell me the impossible.",
  "What's your truth?",
  "Let's create history.",
  "Show me your wonder.",
  "What's your strength?",
  "Let's make it matter.",
  "What's your light?",
  "Tell me your dreams, [nickname].",
  "What's your vision?",
  "Let's create forever.",
  "Show me your courage.",
  "What's your drive?",
  "Let's make it real.",
  "What's your voice?",
  "Tell me something real.",
  "What's your truth, [nickname]?",
  "Let's create magic.",
  "Show me your authenticity.",
  "What's your impact?",
  "Let's make it unforgettable.",
];

export function getRandomPlaceholder(nickname: string = "Master"): string {
  const placeholder = CHAT_PLACEHOLDERS[Math.floor(Math.random() * CHAT_PLACEHOLDERS.length)];
  return placeholder.replace(/\[nickname\]/g, nickname);
}

export function getPlaceholderByIndex(index: number, nickname: string = "Master"): string {
  const placeholder = CHAT_PLACEHOLDERS[index % CHAT_PLACEHOLDERS.length];
  return placeholder.replace(/\[nickname\]/g, nickname);
}
