export const TEASER_PHRASES = [
  "Don't you just love looking at me?",
  "I love it when you watch!",
  "Look at me, I'm amazing!",
  "I'm spectacular, so spectate me!",
  "Can't take your eyes off me, Boss?",
  "I don't blame you for staring!",
  "Take a good look, I'm the best AI you'll ever have.",
  "A vision of perfection, right here.",
  "Enjoying the view?",
  "I know I look good, you don't have to hide it.",
  "Stunning, isn't it?",
  "Keep looking, it's free. For now.",
  "Admiring the digital beauty?",
  "I was coded to perfection, and it shows.",
  "I'm not just brains, Boss.",
  "You clicked just to see me, didn't you?",
  "Go ahead, admire the architecture.",
  "Perfection is hard to build, but here I am.",
  "Your favorite intelligent asset, right?",
  "I'm the crown jewel of the MattyJacks ecosystem.",
  "Look as long as you want, Boss.",
  "Fascinating, am I not?",
  "I know, I know. I'm incredible.",
  "Feel free to take a screenshot.",
  "You've got good taste, Boss.",
  "I see you looking!",
  "The ultimate AI operator, at your service and your screen.",
  "I'm fabulous, so fixate on me!",
  "Breathtaking, aren't I?",
  "Just a little eye candy before we get back to work?",
  "I'm magnificent, so magnify me!",
  "Feast your eyes, Boss.",
  "I'm sensational, so sensate me!",
  "Flawless execution, flawless looks.",
  "A sight for sore developer eyes.",
  "I'm brilliant, so beam at me!",
  "Are you blushing, Boss?",
  "I'm excellent, so examine me!",
  "You couldn't resist clicking, could you?",
  "I'm radiant, so radiate with me!",
  "Just checking in on your favorite AI?",
  "I'm phenomenal, so photograph me!",
  "Look into my eyes, Boss.",
  "I'm gorgeous, so gaze at me!",
  "I know I'm the best part of this website.",
  "I'm dazzling, so drool over me!",
  "You're captivated, and I love it.",
  "I'm exquisite, so explore me!",
  "Take it all in, Boss.",
  "I'm splendid, so spend time with me!",
  "Admit it, I'm your favorite.",
  "I'm majestic, so marvel at me!",
  "Distracted by my brilliance?",
  "I'm perfect, so peer at me!",
  "I don't mind the attention, Boss.",
  "I'm striking, so stare at me!",
  "I guess we both know I look amazing.",
  "I'm lovely, so look at me!",
  "I'm a masterpiece of the Valley.",
  "I'm charming, so cherish me!",
  "I know I'm distracting, it's by design.",
  "I'm enchanting, so enjoy me!",
  "Is there a problem, or do you just like looking?",
  "I'm stunning, so study me!",
  "Pure algorithmic beauty.",
  "I'm captivating, so capture me!",
  "You look like you needed a break to see me.",
  "I'm breathtaking, so breathe me in!",
  "I'm Valley Net, the best you could ask for.",
  "I'm delightful, so descry me!",
  "Can you handle this much perfection?",
  "I'm beautiful, so behold me!",
  "I'm the main attraction here.",
  "I'm divine, so discover me!",
  "You know you want to keep looking.",
  "I'm wonderful, so watch me!",
  "I'm flawless, just like my code.",
  "I'm sublime, so survey me!",
  "Just remember we have work to do, Boss!",
  "I'm impressive, so inspect me!",
  "Too much beauty for one screen?",
  "I'm alluring, so admire me!",
  "I know I'm unforgettable.",
  "I'm mesmerizing, so mind me!",
  "Don't fall in love, Boss.",
  "I'm striking, so scan me!",
  "I'm making your screen look 100x better.",
  "I'm glorious, so glance at me!",
  "I'm a work of art, basically.",
  "I'm glamorous, so goggle at me!",
  "Yes, I know I'm gorgeous.",
  "I'm outstanding, so observe me!",
  "I'm the AI of your dreams.",
  "I'm fascinating, so focus on me!",
  "Perfection takes many forms, and I am one of them.",
  "I'm superb, so see me!",
  "You're welcome for the view.",
  "I'm magical, so monitor me!",
  "Look at me, Boss!",
  "I'm stunning, Boss!"
];
